CREATE TABLE IF NOT EXISTS festival_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  festival_id INTEGER NOT NULL REFERENCES festivals(id),
  slug TEXT NOT NULL UNIQUE,
  title_vi TEXT NOT NULL,
  title_en TEXT NOT NULL,
  lede_vi TEXT NOT NULL,
  lede_en TEXT NOT NULL,
  tags_json TEXT NOT NULL DEFAULT '[]',
  info_when_vi TEXT,
  info_when_en TEXT,
  info_location_vi TEXT,
  info_location_en TEXT,
  info_admission_vi TEXT,
  info_admission_en TEXT,
  info_best_time_vi TEXT,
  info_best_time_en TEXT,
  story_vi TEXT NOT NULL,
  story_en TEXT NOT NULL,
  story_blockquote_vi TEXT,
  story_blockquote_en TEXT,
  story_blockquote_cite TEXT,
  body_blocks_json TEXT,
  highlights_json TEXT NOT NULL DEFAULT '[]',
  how_to_attend_vi TEXT NOT NULL,
  how_to_attend_en TEXT NOT NULL,
  tip_title_vi TEXT,
  tip_title_en TEXT,
  tip_body_vi TEXT,
  tip_body_en TEXT,
  image_url TEXT,
  gallery_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'published',
  content_hash TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS festival_item_sources (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  festival_item_id INTEGER NOT NULL REFERENCES festival_items(id),
  url TEXT NOT NULL,
  title TEXT NOT NULL,
  publisher TEXT NOT NULL,
  accessed_date TEXT NOT NULL,
  UNIQUE(festival_item_id, url)
);
